#
# basic setup
#
- name: role brief
  debug:
    msg:
      - ssh_port - {{ ssh_port }}
  tags: debug

- name: set timezone to UTC
  timezone:
    hwclock: UTC
    name: UTC
  tags:
    - basic
    - timezone

- name: make sure authorized_key exists
  authorized_key:
    user: root
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: add_authorized_key
  tags:
    - basic
    - ssh
    - debug

- name: check authorized_keys permission
  file: path=~/.ssh/authorized_keys
        mode=0600
  tags:
    - basic
    - ssh
    - debug

- name: update server hostname
  hostname: name={{ inventory_hostname }}
  tags:
    - basic
    - ssh
    - hostname

- name: enable PermitRootLogin
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin '
    insertafter: '^#PermitRootLogin '
    line: 'PermitRootLogin yes'
  notify: restart sshd
  tags:
    - basic
    - ssh
    - ssh_root_login

- name: disable PasswordAuthentication for password logins
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication '
    insertafter: '^#PasswordAuthentication '
    line: 'PasswordAuthentication no'
  notify: restart sshd
  tags:
    - basic
    - ssh
    - ssh_port

- name: disable PermitEmptyPasswords
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitEmptyPasswords '
    insertafter: '^#PermitEmptyPasswords '
    line: 'PermitEmptyPasswords no'
  notify: restart sshd
  tags:
    - basic
    - ssh
    - ssh_port

- name: disable GSSAPIAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^GSSAPIAuthentication '
    insertafter: '^#GSSAPIAuthentication '
    line: 'GSSAPIAuthentication no'
  notify: restart sshd
  tags:
    - basic
    - ssh
    - ssh_port

- name: disable KerberosAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^KerberosAuthentication '
    insertafter: '^#KerberosAuthentication '
    line: 'KerberosAuthentication no'
  notify: restart sshd
  tags:
    - basic
    - ssh
    - ssh_port

- name: disable ChallengeResponseAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication '
    insertafter: '^#ChallengeResponseAuthentication '
    line: 'ChallengeResponseAuthentication no'
  notify: restart sshd
  tags:
    - basic
    - ssh
    - ssh_port

- name: enable UsePAM
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^UsePAM '
    insertafter: '^#UsePAM '
    line: 'UsePAM yes'
  notify: restart sshd
  tags:
    - basic
    - ssh
    - ssh_port

# default `KexAlgorithms` can be found in `man sshd_config`
# get modern suggestion from https://observatory.mozilla.org/
# more ref: https://security.stackexchange.com/q/39756
- name: update KexAlgorithms
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^KexAlgorithms '
    insertafter: '^#KexAlgorithms '
    line: 'KexAlgorithms curve25519-sha256,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256'
  notify: restart sshd
  tags:
    - basic
    - ssh
    - ssh_port

- name: update Ciphers
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Ciphers '
    insertafter: '^#Ciphers '
    line: 'Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
  notify: restart sshd
  tags:
    - basic
    - ssh
    - ssh_port

- name: update MACs
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MACs '
    insertafter: '^#MACs '
    line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
  notify: restart sshd
  tags:
    - basic
    - ssh
    - ssh_port

- name: change SSH port to {{ ssh_port }}
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^Port "
              insertafter="^#Port "
              line="Port {{ ssh_port }}"
  notify: restart sshd
  tags:
    - basic
    - ssh
    - ssh_port

- name: get distribution version
  debug: msg={{ ansible_distribution_version }}
  tags: debug

- name: get architecture
  debug: msg={{ ansible_architecture }}
  tags: debug

- name: do apt update
  apt:
    name: '*'
    state: latest
  tags:
    - basic
    - update

- name: install essential packages
  apt:
    name: "{{ debian_common_packages }}"
    state: present
  tags:
    - basic
    - repo

- name: tweak sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    ignoreerrors: yes
  with_items: "{{ sysctl_params }}"
  # Allow erros for OpenVZ serviers
  ignore_errors: yes
  tags:
    - sysctl

- name: disable email for cron
  cron:
    name: MAILTO
    env: yes
    value: ""
  tags:
    - cron
